obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.3, -0.3], [0.3, 0.3], [-0.3,0.3], [-0.3, -0.3]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.6


static:
  map_topic: /map
  subscribe_to_updates: true