local_costmap:
  global_frame: odom
  robot_base_frame: summit_base_footprint
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0
  obstacles_laser:
      observation_sources: laser
      laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
  plugins:
  - {name: obstacles_laser,            type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}
  